/**
 * seed.js — Database seed script for the Car Rental application.
 *
 * Connects to MongoDB, drops the existing cars collection, and inserts a fresh
 * set of sample cars covering multiple categories (Sedan, SUV, Luxury, Sports,
 * Electric, Economy) and Indian states/cities.
 *
 * Usage:
 *   node seed.js
 *
 * The MONGODB_URI environment variable (or .env file) determines the target
 * database. Defaults to mongodb://localhost:27017/car_rental.
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Car = require('./models/Car');

const cars = [
  // ── Sedans ─────────────────────────────────────────────
  {
    name: 'Maruti Swift Dzire',
    brand: 'Maruti Suzuki',
    category: 'Sedan',
    pricePerDay: 1800,
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.3,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Pune',
    features: ['Air Conditioning', 'Bluetooth', 'Power Steering'],
    description: 'India\'s most popular compact sedan, perfect for city commutes.',
  },
  {
    name: 'Honda City',
    brand: 'Honda',
    category: 'Sedan',
    pricePerDay: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.5,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Mumbai',
    features: ['Sunroof', 'Lane Watch Camera', 'Cruise Control'],
    description: 'Premium sedan offering a perfect blend of comfort and performance.',
  },
  {
    name: 'Hyundai Verna',
    brand: 'Hyundai',
    category: 'Sedan',
    pricePerDay: 2300,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.4,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Pune',
    features: ['Ventilated Seats', 'Bose Audio', 'ADAS Suite'],
    description: 'Feature-packed sedan with sporty styling and a refined interior.',
  },
  {
    name: 'Skoda Slavia',
    brand: 'Skoda',
    category: 'Sedan',
    pricePerDay: 2800,
    imageUrl: 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.5,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Bangalore',
    features: ['1.5L TSI Engine', 'DSG Gearbox', 'Wireless Charging'],
    description: 'European craftsmanship meets Indian roads — punchy TSI engine.',
  },
  {
    name: 'Toyota Camry Hybrid',
    brand: 'Toyota',
    category: 'Sedan',
    pricePerDay: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.7,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Mysore',
    features: ['Self-Charging Hybrid', 'JBL Audio', 'Panoramic Sunroof'],
    description: 'Premium hybrid executive sedan with exceptional fuel efficiency.',
  },
  {
    name: 'Honda Accord',
    brand: 'Honda',
    category: 'Sedan',
    pricePerDay: 5500,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.6,
    isAvailable: false,
    state: 'Karnataka',
    place: 'Mangalore',
    features: ['2.0L Hybrid Powertrain', 'Honda Sensing', 'Leather Interior'],
    description: 'Flagship executive sedan combining comfort and technology.',
  },
  // ── SUVs ───────────────────────────────────────────────
  {
    name: 'Maruti Suzuki Brezza',
    brand: 'Maruti Suzuki',
    category: 'SUV',
    pricePerDay: 2200,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.4,
    isAvailable: true,
    state: 'Delhi',
    place: 'Dwarka',
    features: ['Sunroof', 'Head-Up Display', 'Connect 360'],
    description: 'Compact SUV with bold styling and feature-rich cabin.',
  },
  {
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    category: 'SUV',
    pricePerDay: 2800,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.5,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Pune',
    features: ['Panoramic Sunroof', 'ADAS Level 2', 'Bose 8-Speaker Sound'],
    description: 'India\'s top-selling mid-size SUV, loved for its versatility.',
  },
  {
    name: 'Kia Seltos',
    brand: 'Kia',
    category: 'SUV',
    pricePerDay: 2900,
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.6,
    isAvailable: true,
    state: 'Delhi',
    place: 'New Delhi',
    features: ['10.25" Dual Displays', 'Bose 8-Speaker', 'Drive Mode Select'],
    description: 'Award-winning SUV with segment-best technology and design.',
  },
  {
    name: 'Tata Harrier',
    brand: 'Tata',
    category: 'SUV',
    pricePerDay: 3200,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.5,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Nagpur',
    features: ['OMEGARC Platform', 'JBL Audio', 'iRA Connected Car'],
    description: 'Bold and muscular SUV with Land Rover-derived platform.',
  },
  {
    name: 'MG Hector Plus',
    brand: 'MG',
    category: 'SUV',
    pricePerDay: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1571987502227-b74777ff6b5e?w=400',
    seats: 7,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.3,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Madurai',
    features: ['14-inch Touchscreen', 'i-SMART Connectivity', 'Captain Seats'],
    description: 'Feature-loaded 7-seater SUV with India\'s largest touchscreen.',
  },
  {
    name: 'Jeep Compass',
    brand: 'Jeep',
    category: 'SUV',
    pricePerDay: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.4,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Mangalore',
    features: ['4x4 Trailhawk', 'Uconnect 5', 'McIntosh Audio'],
    description: 'Premium off-road capable SUV with authentic Jeep heritage.',
  },
  {
    name: 'Toyota Fortuner',
    brand: 'Toyota',
    category: 'SUV',
    pricePerDay: 6500,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.7,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Mysore',
    features: ['4WD System', 'Toyota Safety Sense', 'Dual Zone Climate'],
    description: 'King of Indian roads — unstoppable 7-seater SUV.',
  },
  {
    name: 'Ford Endeavour',
    brand: 'Ford',
    category: 'SUV',
    pricePerDay: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.5,
    isAvailable: false,
    state: 'Telangana',
    place: 'Warangal',
    features: ['Terrain Management System', 'SYNC 3', '360° Camera'],
    description: 'Rugged 7-seater built for adventure with Ford Power.',
  },
  {
    name: 'Land Rover Defender',
    brand: 'Land Rover',
    category: 'SUV',
    pricePerDay: 15000,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.8,
    isAvailable: true,
    state: 'Telangana',
    place: 'Hyderabad',
    features: ['Terrain Response 2', 'Wade Sensing', 'Configurable Terrain'],
    description: 'Iconic off-roader with luxury appointments and supreme capability.',
  },
  // ── Economy ────────────────────────────────────────────
  {
    name: 'Maruti Alto K10',
    brand: 'Maruti Suzuki',
    category: 'Economy',
    pricePerDay: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.1,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Mysore',
    features: ['CNG Compatible', 'Idle Start-Stop', 'Rear Defogger'],
    description: 'India\'s most affordable car — efficient and easy to drive.',
  },
  {
    name: 'Hyundai i10 Grand',
    brand: 'Hyundai',
    category: 'Economy',
    pricePerDay: 1400,
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.2,
    isAvailable: true,
    state: 'Delhi',
    place: 'Dwarka',
    features: ['Wireless Charging', '8-inch Touchscreen', 'Rear Camera'],
    description: 'Premium hatchback packing big-car features in a small package.',
  },
  {
    name: 'Tata Tiago',
    brand: 'Tata',
    category: 'Economy',
    pricePerDay: 1500,
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.3,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Nagpur',
    features: ['iRA Connected Car', 'Harman Sound', 'Voice Commands'],
    description: 'Stylish hatchback with standout design and connected features.',
  },
  {
    name: 'Renault Kwid',
    brand: 'Renault',
    category: 'Economy',
    pricePerDay: 1300,
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.0,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Mangalore',
    features: ['MediaNav Touchscreen', 'Digital Cluster', 'Rear Camera'],
    description: 'SUV-inspired hatchback at a budget-friendly price point.',
  },
  {
    name: 'Maruti WagonR CNG',
    brand: 'Maruti Suzuki',
    category: 'Economy',
    pricePerDay: 1600,
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.2,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Coimbatore',
    features: ['S-CNG Technology', 'SmartPlay Studio', 'SmartPlay Cast'],
    description: 'India\'s best-selling CNG car — economical and roomy.',
  },
  // ── Luxury ─────────────────────────────────────────────
  {
    name: 'BMW 5 Series',
    brand: 'BMW',
    category: 'Luxury',
    pricePerDay: 10000,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.8,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Mumbai',
    features: ['Gesture Control', 'Harman Kardon Audio', 'Massage Seats'],
    description: 'The benchmark executive sedan — performance meets luxury.',
  },
  {
    name: 'Mercedes-Benz E-Class',
    brand: 'Mercedes-Benz',
    category: 'Luxury',
    pricePerDay: 11000,
    imageUrl: 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.9,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Mysore',
    features: ['MBUX Infotainment', 'Air Body Control', 'Burmester Audio'],
    description: 'The pinnacle of business excellence on four wheels.',
  },
  {
    name: 'Audi A6',
    brand: 'Audi',
    category: 'Luxury',
    pricePerDay: 9500,
    imageUrl: 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.7,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Chennai',
    features: ['Virtual Cockpit Plus', 'Bang & Olufsen Audio', 'MMI Touch'],
    description: 'Quattro AWD luxury sedan with progressive technology.',
  },
  {
    name: 'Jaguar XE',
    brand: 'Jaguar',
    category: 'Luxury',
    pricePerDay: 8500,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.6,
    isAvailable: false,
    state: 'Delhi',
    place: 'New Delhi',
    features: ['Meridian Sound', 'All Surface Progress Control', 'InControl Touch Pro'],
    description: 'Dynamic British sports saloon with feline elegance.',
  },
  {
    name: 'Volvo S90',
    brand: 'Volvo',
    category: 'Luxury',
    pricePerDay: 12000,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.8,
    isAvailable: true,
    state: 'Telangana',
    place: 'Hyderabad',
    features: ['Pilot Assist', 'Bowers & Wilkins Audio', 'Air Suspension'],
    description: 'Scandinavian luxury redefined — safety-first executive sedan.',
  },
  {
    name: 'Lexus ES 300h',
    brand: 'Lexus',
    category: 'Luxury',
    pricePerDay: 13000,
    imageUrl: 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.9,
    isAvailable: true,
    state: 'Telangana',
    place: 'Nizamabad',
    features: ['Self-Charging Hybrid', 'Mark Levinson Audio', 'Lexus Safety+'],
    description: 'Ultra-smooth hybrid luxury sedan with Japanese craftsmanship.',
  },
  // ── Sports ─────────────────────────────────────────────
  {
    name: 'Hyundai i20 N Line',
    brand: 'Hyundai',
    category: 'Sports',
    pricePerDay: 3500,
    imageUrl: 'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.5,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Mumbai',
    features: ['N Line Sport Suspension', 'Sport Seats', 'Drive Mode Select'],
    description: 'Performance-tuned hot hatch for the spirited Indian driver.',
  },
  {
    name: 'VW Polo GT',
    brand: 'Volkswagen',
    category: 'Sports',
    pricePerDay: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.6,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Chennai',
    features: ['1.0L TSI Engine', 'DSG Gearbox', 'Sport Suspension'],
    description: 'Fun-to-drive German hot hatch with sharp handling.',
  },
  {
    name: 'BMW M340i',
    brand: 'BMW',
    category: 'Sports',
    pricePerDay: 14000,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.9,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Bangalore',
    features: ['B58 Inline-6 Turbo', 'xDrive AWD', 'Adaptive M Suspension'],
    description: 'M Performance accelerates with 374 bhp of inline-6 fury.',
  },
  {
    name: 'Porsche Macan',
    brand: 'Porsche',
    category: 'Sports',
    pricePerDay: 16000,
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.8,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Coimbatore',
    features: ['PASM Sport Suspension', 'Sport Chrono Package', 'Porsche Connect'],
    description: 'The most successful Porsche ever — sporty SUV perfection.',
  },
  {
    name: 'Audi TT',
    brand: 'Audi',
    category: 'Sports',
    pricePerDay: 13500,
    imageUrl: 'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=400',
    seats: 4,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.7,
    isAvailable: false,
    state: 'Telangana',
    place: 'Nizamabad',
    features: ['Audi Virtual Cockpit', 'quattro AWD', 'Drive Select'],
    description: 'Iconic sports coupe with muscular design and quattro grip.',
  },
  // ── Electric ───────────────────────────────────────────
  {
    name: 'Tata Nexon EV Max',
    brand: 'Tata',
    category: 'Electric',
    pricePerDay: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.5,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Mumbai',
    features: ['437 km Range', 'iRA Connected Car', 'Ziptron Technology'],
    description: 'India\'s best-selling EV with maximum range and smart features.',
  },
  {
    name: 'MG ZS EV',
    brand: 'MG',
    category: 'Electric',
    pricePerDay: 3500,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.4,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Pune',
    features: ['461 km Range', 'i-SMART Technology', 'panoramic Roof'],
    description: 'Feature-packed electric SUV with impressive real-world range.',
  },
  {
    name: 'Hyundai Ioniq 5',
    brand: 'Hyundai',
    category: 'Electric',
    pricePerDay: 7000,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.8,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Bangalore',
    features: ['800V Ultra-Fast Charging', 'V2L Technology', 'HTRAC AWD'],
    description: 'Futuristic crossover on dedicated EV platform — 590 km range.',
  },
  {
    name: 'Kia EV6',
    brand: 'Kia',
    category: 'Electric',
    pricePerDay: 7500,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.8,
    isAvailable: false,
    state: 'Tamil Nadu',
    place: 'Chennai',
    features: ['800V Charging', 'GT-Line Aero', '77.4 kWh Battery'],
    description: 'GT-inspired EV crossover with supercar-level acceleration.',
  },
  {
    name: 'BMW iX',
    brand: 'BMW',
    category: 'Electric',
    pricePerDay: 14000,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.9,
    isAvailable: true,
    state: 'Telangana',
    place: 'Hyderabad',
    features: ['630 km Range', 'Curved Display', 'Bowers & Wilkins Diamond Audio'],
    description: 'BMW\'s flagship electric SUV — the future of luxury mobility.',
  },
  {
    name: 'Mercedes-Benz EQS',
    brand: 'Mercedes-Benz',
    category: 'Electric',
    pricePerDay: 18000,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.9,
    isAvailable: true,
    state: 'Delhi',
    place: 'New Delhi',
    features: ['857 km Range', 'MBUX Hyperscreen', 'Air Suspension'],
    description: 'The electric S-Class — pinnacle of electric luxury.',
  },
  // ── Diesel SUVs & MPVs ─────────────────────────────────
  {
    name: 'Mahindra Thar',
    brand: 'Mahindra',
    category: 'SUV',
    pricePerDay: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 4,
    transmission: 'Manual',
    fuelType: 'Diesel',
    rating: 4.6,
    isAvailable: true,
    state: 'Telangana',
    place: 'Warangal',
    features: ['4WD Low Range', 'Differential Lock', 'Waterproof Interior'],
    description: 'The ultimate off-road icon — go anywhere, anytime.',
  },
  {
    name: 'Mahindra XUV700',
    brand: 'Mahindra',
    category: 'SUV',
    pricePerDay: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.7,
    isAvailable: true,
    state: 'Karnataka',
    place: 'Bangalore',
    features: ['Advanced Driver Assistance', 'Sony 3D Sound', 'Panoramic Sunroof'],
    description: 'Segment-disrupting feature flagship at an accessible price.',
  },
  {
    name: 'Isuzu D-Max V-Cross',
    brand: 'Isuzu',
    category: 'SUV',
    pricePerDay: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Diesel',
    rating: 4.4,
    isAvailable: true,
    state: 'Telangana',
    place: 'Warangal',
    features: ['4WD Hi/Lo', '1 Tonne Payload', 'Rough Terrain Mode'],
    description: 'India\'s most capable lifestyle pickup truck.',
  },
  {
    name: 'Toyota Innova Crysta',
    brand: 'Toyota',
    category: 'SUV',
    pricePerDay: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1571987502227-b74777ff6b5e?w=400',
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.6,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Coimbatore',
    features: ['Captain Seats', 'Auto Climate Control', 'Child Seat Anchors'],
    description: 'India\'s most trusted MPV for family and business travel.',
  },
  {
    name: 'Kia Carnival',
    brand: 'Kia',
    category: 'SUV',
    pricePerDay: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1571987502227-b74777ff6b5e?w=400',
    seats: 8,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.7,
    isAvailable: true,
    state: 'Telangana',
    place: 'Hyderabad',
    features: ['VIP Lounge Rear Seats', 'Harman Kardon Audio', 'Sliding Doors'],
    description: 'Premium minivan redefining luxury people-mover segment.',
  },
  {
    name: 'Volkswagen Tiguan',
    brand: 'Volkswagen',
    category: 'SUV',
    pricePerDay: 5500,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.5,
    isAvailable: true,
    state: 'Delhi',
    place: 'New Delhi',
    features: ['4MOTION AWD', 'IQ.DRIVE', 'DCC Adaptive Chassis'],
    description: 'Refined German import SUV with sophisticated driving dynamics.',
  },
  // ── More Models ────────────────────────────────────────
  {
    name: 'Skoda Octavia',
    brand: 'Skoda',
    category: 'Sedan',
    pricePerDay: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.6,
    isAvailable: true,
    state: 'Maharashtra',
    place: 'Nagpur',
    features: ['2.0L TSI 190PS', 'Columbus Navigation', 'Canton Sound System'],
    description: 'Spacious and sporty executive estate with go-fast DNA.',
  },
  {
    name: 'Maruti Grand Vitara',
    brand: 'Maruti Suzuki',
    category: 'SUV',
    pricePerDay: 3200,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.4,
    isAvailable: true,
    state: 'Delhi',
    place: 'Rohini',
    features: ['Hybrid Powertrain', 'AllGrip Select AWD', 'Panoramic Sunroof'],
    description: 'Powerful hybrid SUV with all-wheel drive capability.',
  },
  {
    name: 'Honda WR-V',
    brand: 'Honda',
    category: 'SUV',
    pricePerDay: 2200,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    rating: 4.3,
    isAvailable: false,
    state: 'Delhi',
    place: 'Rohini',
    features: ['High Ground Clearance', 'Honda Sensing', 'Rear Wiper'],
    description: 'Elevated hatchback bridging the gap to a full SUV.',
  },
  {
    name: 'Renault Duster',
    brand: 'Renault',
    category: 'SUV',
    pricePerDay: 2800,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Diesel',
    rating: 4.3,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Madurai',
    features: ['4WD Option', 'High Clearance', 'MediaNav Evolution'],
    description: 'Rugged no-nonsense SUV made for Indian roads.',
  },
  {
    name: 'Ford EcoSport',
    brand: 'Ford',
    category: 'SUV',
    pricePerDay: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.2,
    isAvailable: true,
    state: 'Delhi',
    place: 'Dwarka',
    features: ['SYNC 3', 'B&O Play Audio', 'FordPass Connect'],
    description: 'Plucky compact SUV with punchy EcoBoost engine.',
  },
  {
    name: 'Tata Safari',
    brand: 'Tata',
    category: 'SUV',
    pricePerDay: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.5,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Madurai',
    features: ['iRA Connected Car', 'JBL Premium Audio', 'Terrain Mode'],
    description: 'Reborn Safari — powerful 7-seater SUV with modern design.',
  },
  {
    name: 'Hyundai Tucson',
    brand: 'Hyundai',
    category: 'SUV',
    pricePerDay: 5500,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.6,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Chennai',
    features: ['Parametric Hidden Lights', 'HTRAC AWD', 'ADAS Level 2'],
    description: 'Striking design meets premium comfort in this flagship SUV.',
  },
  {
    name: 'Skoda Kodiaq',
    brand: 'Skoda',
    category: 'SUV',
    pricePerDay: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.6,
    isAvailable: true,
    state: 'Tamil Nadu',
    place: 'Coimbatore',
    features: ['7-Seat Layout', 'Canton Sound', 'Adaptive Cruise Control'],
    description: 'Premium 7-seat flagship SUV with European sophistication.',
  },
  {
    name: 'Citroen C5 Aircross',
    brand: 'Citroen',
    category: 'SUV',
    pricePerDay: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    rating: 4.4,
    isAvailable: true,
    state: 'Telangana',
    place: 'Nizamabad',
    features: ['Advanced Comfort Suspension', 'Progressive Hydraulic Cushions', 'DS Audio'],
    description: 'French design icon with magic carpet ride quality.',
  },
  {
    name: 'Nio ET7',
    brand: 'Nio',
    category: 'Electric',
    pricePerDay: 9000,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.7,
    isAvailable: false,
    state: 'Delhi',
    place: 'Rohini',
    features: ['Battery Swap Technology', 'NIO Pilot ADAS', 'NOMI AI'],
    description: 'Smart electric flagship sedan with swappable battery system.',
  },
];


async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await Car.deleteMany({});
    console.log('🗑️  Cleared existing cars');

    const inserted = await Car.insertMany(cars);
    console.log(`🚗 Seeded ${inserted.length} cars`);

    await mongoose.disconnect();
    console.log('✅ Done. MongoDB disconnected.');
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
